package com.luxoft.blockchainlab.corda.hyperledger.indy.flow

import co.paralleluniverse.fibers.Suspendable
import net.corda.core.flows.*


/**
 * Flow to revoke previously issued claim
 */
object RevokeClaimFlow {

    /**
     * @param claimId           claim id generated by issueClaimFlow
     */
    @InitiatingFlow
    @StartableByRPC
    open class Issuer(private val claimId: String) : FlowLogic<Unit>() {

        @Suspendable
        override fun call() {
            try {
                // query vault for claim with id = claimid
                val claim = getIndyClaimState(claimId)?.state?.data
                    ?: throw RuntimeException("No such claim in vault")

                val revRegId = claim.claimInfo.claim.revRegId!!
                val credRevId = claim.claimInfo.credRevocId!!

                // revoke that claim
                indyUser().revokeClaim(revRegId, credRevId)

            } catch (ex: Exception) {
                logger.error("", ex)
                throw FlowException(ex.message)
            }
        }
    }
}